### PR TITLE
Small suggested edits

### PR DESCRIPTION
**Pull request by gbinal**
a few typos and hyperlinks

### CODE REVIEW

**Comment by kishoregh** [comment]
Thanks.

**Comment by kishoregh** [comment]
Thank you Gray for your help in fixing the doc.

There are few references of Sam in Auctions api file folders' names, trying
to fix, but can't see the edit button. Could you please help?
[image: Inline image 1]

Thank you,

_Kishore Nedurumalli_
Asset&Transportation Div
Office of the GSA CIO
Phone: 443-722-2743

**Comment by gbinal** [comment]
I may be misunderstanding, so let me know if you mean otherwise.  

There's not an edit functionality for folder names, rather it's a matter of editing the file name (which is available at the same time as editing the contents of a file).  When editing the name of a file that is nested in a folder, the folder for that file can be edited by pressing backspace/delete at the front of the file name field.  If you need to change a folder  that has a bunch of files in it, then it's best to use a client (command line/github for windows/github  for mac).  Let me know specifics if you need a hand or holler if you want to quickly discuss in person.

**Comment by kishoregh** [comment]
Let's make sure we are on the same page.

In my screen shot in the above email, the first folder name is " _data "
and I believe the description of it is "adding in sam_api material".
I'm referring about changing the "adding in sam_api material "  to
"adding in auctions_api material"

Please let me know your explanation above works for this change.

Thank you,

_Kishore Nedurumalli_
Asset&Transportation Div
Office of the GSA CIO
Phone: 443-722-2743

**Comment by gbinal** [comment]
Ah - looking at your screenshot now (pasted below).  

What you're seeing there is nothing to worry about - they are the descriptions for the most recent commits to those folders or files.  They don't impact what visitors see at gsa.github.io/auctions_api/ at all.  That said, they will change to be whatever you include as the short description of the next commit in those folders or files.  

image

**Comment by gbinal** [comment]
p.s.  I'd suggest not worrying about it.

**Pull request merged**
